from __future__ import annotations

from typing import Protocol

from app.domain.models import DonationRecord


class DonationRepository(Protocol):
    def add(self, donation: DonationRecord) -> None: ...
    def get(self, donation_id: str) -> DonationRecord | None: ...
    def update(self, donation: DonationRecord) -> None: ...
    def list_pending(self, church_id: str) -> list[DonationRecord]: ...
